-- Migración: Si tu base Neon tiene tablas con id UUID (p. ej. 001_create_admin_schema.sql),
-- la app usa ids como "proj-1" o UUID en texto. Ejecutá este script en el SQL Editor de Neon.
-- Error que soluciona: "invalid input syntax for type uuid: 'proj-1'"

-- projects
DO $$ BEGIN ALTER TABLE public.projects ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.projects ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.projects ALTER COLUMN created_by TYPE VARCHAR(36) USING created_by::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- services
DO $$ BEGIN ALTER TABLE public.services ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ALTER COLUMN created_by TYPE VARCHAR(36) USING created_by::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- blog_posts
DO $$ BEGIN ALTER TABLE public.blog_posts ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.blog_posts ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.blog_posts ALTER COLUMN author_id TYPE VARCHAR(36) USING author_id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- contact_submissions
DO $$ BEGIN ALTER TABLE public.contact_submissions ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.contact_submissions ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- testimonials
DO $$ BEGIN ALTER TABLE public.testimonials ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.testimonials ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.testimonials ALTER COLUMN created_by TYPE VARCHAR(36) USING created_by::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- hero_images
DO $$ BEGIN ALTER TABLE public.hero_images ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.hero_images ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- certifications
DO $$ BEGIN ALTER TABLE public.certifications ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.certifications ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- clients
DO $$ BEGIN ALTER TABLE public.clients ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.clients ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- users (admins)
DO $$ BEGIN ALTER TABLE public.users ALTER COLUMN id DROP DEFAULT; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.users ALTER COLUMN id TYPE VARCHAR(36) USING id::text; EXCEPTION WHEN OTHERS THEN NULL; END $$;
